{{ ansible_managed | comment }}

version: '3'
services:
  grafana:
    image: grafana/grafana-oss:10.0.1
    networks:
      {{ proxy_network }}:
      {{ db_network }}:
    volumes:
     - "{{grafana_data_location}}:/var/lib/grafana"
    environment:
     - GF_SERVER_ROOT_URL=https://%(domain)s/
     - GF_SERVER_ENFORCE_DOMAIN=true
     - GF_SERVER_DOMAIN={{ monitoring_domain }}
    restart: always
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`{{ monitoring_domain }}`)"
        - "traefik.http.routers.grafana.entrypoints=https"
        - "traefik.http.routers.grafana.middlewares=compress@file"
        - "traefik.http.routers.grafana.tls.certresolver={{ traefik_certresolver }}"
        - "traefik.http.services.grafana.loadbalancer.server.port={{ grafana_port }}"
        - "traefik.docker.network={{ proxy_network }}"
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
 
networks:
  {{ proxy_network }}:
    external: true
  {{ db_network }}:
    external: true
